# Generated by Django 3.1.3 on 2020-11-21 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=256)),
                ('codigo', models.CharField(max_length=13, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
